#!/bin/bash

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")"; cd ..; pwd)"
source ${PROJECT_ROOT}/config.sh

docker run -it \
  -p ${SERVER_PORT_1}:${SERVER_PORT_1}  \
  -p ${SERVER_PORT_2}:${SERVER_PORT_2}  \
  --volume ${PROJECT_ROOT}/app:/app \
  --name=${PROJECT_NAME} \
  --rm \
  ${PROJECT_NAME}
